from ._zsrc import ZsrcValidator
from ._zcalendar import ZcalendarValidator
from ._z import ZValidator
from ._ysrc import YsrcValidator
from ._ycalendar import YcalendarValidator
from ._y import YValidator
from ._xsrc import XsrcValidator
from ._xcalendar import XcalendarValidator
from ._x import XValidator
from ._visible import VisibleValidator
from ._vertexcolorsrc import VertexcolorsrcValidator
from ._vertexcolor import VertexcolorValidator
from ._uid import UidValidator
from ._textsrc import TextsrcValidator
from ._text import TextValidator
from ._stream import StreamValidator
from ._showscale import ShowscaleValidator
from ._showlegend import ShowlegendValidator
from ._selectedpoints import SelectedpointsValidator
from ._scene import SceneValidator
from ._reversescale import ReversescaleValidator
from ._opacity import OpacityValidator
from ._name import NameValidator
from ._lightposition import LightpositionValidator
from ._lighting import LightingValidator
from ._legendgroup import LegendgroupValidator
from ._ksrc import KsrcValidator
from ._k import KValidator
from ._jsrc import JsrcValidator
from ._j import JValidator
from ._isrc import IsrcValidator
from ._intensitysrc import IntensitysrcValidator
from ._intensity import IntensityValidator
from ._idssrc import IdssrcValidator
from ._ids import IdsValidator
from ._i import IValidator
from ._hoverlabel import HoverlabelValidator
from ._hoverinfosrc import HoverinfosrcValidator
from ._hoverinfo import HoverinfoValidator
from ._flatshading import FlatshadingValidator
from ._facecolorsrc import FacecolorsrcValidator
from ._facecolor import FacecolorValidator
from ._delaunayaxis import DelaunayaxisValidator
from ._customdatasrc import CustomdatasrcValidator
from ._customdata import CustomdataValidator
from ._contour import ContourValidator
from ._colorscale import ColorscaleValidator
from ._colorbar import ColorBarValidator
from ._color import ColorValidator
from ._cmin import CminValidator
from ._cmax import CmaxValidator
from ._cauto import CautoValidator
from ._autocolorscale import AutocolorscaleValidator
from ._alphahull import AlphahullValidator
