version: 2

updates:
  # Update package versions pinned in uv.lock.
  # Note that these updates only affect what dependency versions we use in the CI;
  # they have no effect on the release artifacts.
  # Still, it's important that we run our CI against the latest dependency versions
  # in order to catch any potential issues early.
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3  # Should match tool.uv.exclude-newer option in pyproject.toml
    groups:
      uv-dependencies:
        patterns:
          - "*"

  # Update pinned versions for third-party GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 3
