"""Utility command runner."""

import argparse
import logging
import json
import os
import platform
import re
import requests
import shutil
import subprocess
from subprocess import check_call
import sys
import time
import tempfile

from codegen import perform_codegen, lint_code, reformat_code


LOGGER = logging.getLogger(__name__)
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
NODE_ROOT = os.path.join(PROJECT_ROOT, "js")
NODE_MODULES = os.path.join(NODE_ROOT, "node_modules")
WIDGET_TARGETS = [
    os.path.join(PROJECT_ROOT, "plotly", "package_data", "widgetbundle.js"),
]

NPM_PATH = os.pathsep.join(
    [
        os.path.join(NODE_ROOT, "node_modules", ".bin"),
        os.environ.get("PATH", os.defpath),
    ]
)


def plotly_js_version():
    """Load plotly.js version from js/package.json."""

    path = os.path.join(PROJECT_ROOT, "js", "package.json")
    with open(path, "rt") as f:
        package_json = json.load(f)
        version = package_json["dependencies"]["plotly.js"]
        version = version.replace("^", "")

    return version


def install_js_deps(local, build=True):
    """Install package.json dependencies using npm.

    When ``build`` is True (the default), also runs ``npm run build`` to
    rebuild the JupyterLab extension and FigureWidget bundles and verifies
    that the widget bundle exists. Pass ``build=False`` when you only need
    to refresh ``node_modules`` / ``package-lock.json`` but don't
    need the bundles rebuilt.
    """

    npmName = "npm"
    if platform.system() == "Windows":
        npmName = "npm.cmd"

    try:
        check_call([npmName, "--version"])
        has_npm = True
    except Exception:
        has_npm = False

    skip_npm = os.environ.get("SKIP_NPM", False)
    if skip_npm:
        LOGGER.info("Skipping npm-installation")
        return

    if not has_npm:
        LOGGER.error(
            "`npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo"
        )

    env = os.environ.copy()
    env["PATH"] = NPM_PATH

    if has_npm:
        LOGGER.info("Installing build dependencies with npm.  This may take a while...")
        check_call(
            [npmName, "install"],
            cwd=NODE_ROOT,
            stdout=sys.stdout,
            stderr=sys.stderr,
        )
        if local is not None:
            # plotly_archive = os.path.join(local, "plotly.js.tgz")
            plotly_archive = local  # Use the local path directly as the archive path
            check_call(
                [npmName, "install", plotly_archive],
                cwd=NODE_ROOT,
                stdout=sys.stdout,
                stderr=sys.stderr,
            )
        if build:
            check_call(
                [npmName, "run", "build"],
                cwd=NODE_ROOT,
                stdout=sys.stdout,
                stderr=sys.stderr,
            )
        os.utime(NODE_MODULES, None)

    if build:
        for target in WIDGET_TARGETS:
            if not os.path.exists(target):
                msg = "Missing file: %s" % target
                raise ValueError(msg)


def overwrite_schema_local(uri):
    """Replace plot-schema.json with local copy."""

    path = os.path.join(PROJECT_ROOT, "codegen", "resources", "plot-schema.json")
    print("Copying local plot-schema.json from %s to %s" % (uri, path))
    shutil.copyfile(uri, path)


def overwrite_schema(url):
    """Replace plot-schema.json with web copy."""

    req = requests.get(url)
    assert req.status_code == 200
    path = os.path.join(PROJECT_ROOT, "codegen", "resources", "plot-schema.json")
    with open(path, "wb") as f:
        f.write(req.content)


def overwrite_bundle_local(uri):
    """Replace minified JavaScript bundle.json with local copy."""

    path = os.path.join(PROJECT_ROOT, "plotly", "package_data", "plotly.min.js")
    print("Copying local plotly.min.js from %s to %s" % (uri, path))
    shutil.copyfile(uri, path)


def overwrite_bundle(url):
    """Replace minified JavaScript bundle.json with web copy."""

    req = requests.get(url)
    print("url:", url)
    assert req.status_code == 200
    path = os.path.join(PROJECT_ROOT, "plotly", "package_data", "plotly.min.js")
    with open(path, "wb") as f:
        f.write(req.content)


def overwrite_plotlyjs_version_file(plotlyjs_version):
    """Replace plotly.js version file."""

    path = os.path.join(PROJECT_ROOT, "plotly", "offline", "_plotlyjs_version.py")
    with open(path, "w") as f:
        f.write(
            """\
# DO NOT EDIT
# This file is generated by the updatebundle commands.py command
__plotlyjs_version__ = "{plotlyjs_version}"
""".format(plotlyjs_version=plotlyjs_version)
        )


def get_latest_commit_info(repo, branch):
    """Get latest commit info from GitHub API."""

    url = "https://api.github.com/repos/{repo}/commits/{branch}".format(
        repo=repo, branch=branch
    )
    req = requests.get(url)
    assert req.status_code == 200, "Failed to fetch commit info: %s" % req.text
    commit = req.json()

    return {
        "vcs_revision": commit["sha"],
        "committer_date": commit["commit"]["committer"]["date"],
    }


def get_bundle_schema_local(local):
    """Get paths to local build files."""

    abs_path_local = os.path.abspath(local)

    # plotly_archive = os.path.join(abs_path_local, "plotly.js.tgz")
    plotly_archive = abs_path_local  # Use the local path directly as the archive path
    plotly_bundle = os.path.join(abs_path_local, "dist/plotly.min.js")
    plotly_schemas = os.path.join(abs_path_local, "dist/plot-schema.json")

    # Check that the files exist
    for path in [plotly_archive, plotly_bundle, plotly_schemas]:
        if not os.path.exists(path):
            raise FileNotFoundError(f"Expected file not found: {path}")

    return plotly_archive, plotly_bundle, plotly_schemas


def get_archive_url(repo, revision):
    """Get URL for the archive of the provided repo and commit from GitHub."""
    archive_url = f"https://github.com/{repo}/tarball/{revision}"
    return archive_url

def github_auth_headers():
    """Auth headers for the GitHub API.

    Downloading Actions artifacts requires authentication even for public
    repos. Use $GITHUB_TOKEN if set (e.g. in CI), otherwise fall back to the
    locally-authenticated `gh` CLI, which manages/refreshes the token itself.
    """
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        token = subprocess.check_output(["gh", "auth", "token"], text=True).strip()
    return {"Authorization": f"Bearer {token}"}


def get_dist_artifact_url(revision):
    """Get the download URL for the dist artifact of the 'Publish Dist'
    plotly.js CI job on GitHub Actions."""

    headers = github_auth_headers()
    runs = requests.get(
        "https://api.github.com/repos/plotly/plotly.js/actions/runs",
        params={"head_sha": revision},
        headers=headers,
    ).json()["workflow_runs"]
    for run in runs:
        for artifact in requests.get(run["artifacts_url"], headers=headers).json()["artifacts"]:
            if artifact["name"] == "dist":
                return artifact["archive_download_url"]
    raise RuntimeError(f"No dist artifact found for revision {revision}")


def update_schema(plotly_js_version):
    """Download latest version of the plot-schema JSON file."""

    url = (
        "https://raw.githubusercontent.com/plotly/plotly.js/"
        "v%s/dist/plot-schema.json" % plotly_js_version
    )
    overwrite_schema(url)


def update_bundle(plotly_js_version):
    """Download latest version of the plotly.js bundle."""

    url = (
        "https://raw.githubusercontent.com/plotly/plotly.js/"
        "v%s/dist/plotly.min.js" % plotly_js_version
    )
    overwrite_bundle(url)

    # Write plotly.js version file
    plotlyjs_version = plotly_js_version
    overwrite_plotlyjs_version_file(plotlyjs_version)


def update_plotlyjs(plotly_js_version, outdir):
    """Update project to a new version of plotly.js."""

    update_bundle(plotly_js_version)
    update_schema(plotly_js_version)
    perform_codegen(outdir)
    install_js_deps(local=None, build=True)


def download_and_extract_tarball(url, download_path, unzip_dir=None, headers=None):
    """Download a tarball from the given URL and save it to the specified destination path.
    Returns the path to the directory the archive was extracted into."""
    print(f"Downloading tarball from {url} to {download_path}")
    with requests.get(url, stream=True, headers=headers) as r:
        r.raise_for_status()
        with open(download_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
    if unzip_dir:
        if not os.path.exists(unzip_dir):
            os.makedirs(unzip_dir)
        else:
            raise FileExistsError(f"Directory {unzip_dir} already exists. Please remove it before extracting.")
    else:
        unzip_dir = tempfile.mkdtemp(dir=os.path.dirname(download_path))
    print(f"Extracting tarball to {unzip_dir}")
    shutil.unpack_archive(download_path, unzip_dir)
    return unzip_dir



# FIXME: switch to argparse
def update_schema_bundle_from_branch(args):
    """Update the plotly.js schema and bundle from the provided dev repo
    and dev branch."""

    # Create temp directory using tempfile
    # Only needed for the non-local case, but nesting everything inside the context manager
    # allows for simpler code
    with tempfile.TemporaryDirectory() as temp_dir:

        if args.local is None:
            build_info = get_latest_commit_info(args.devrepo, args.devbranch)
            archive_url = get_archive_url(
                args.devrepo, build_info["vcs_revision"]
            )
            dist_artifact_url = get_dist_artifact_url(build_info["vcs_revision"])

            # Download and extract the plotly.js archive
            print("Downloading plotly.js repo from:", archive_url)
            repo_archive_path = os.path.join(temp_dir, "plotly.js.tgz")
            repo_unzip_dir = download_and_extract_tarball(archive_url, repo_archive_path)
            # The repo tarball extracts into a single top-level directory
            repo_extracted_path = os.path.join(
                repo_unzip_dir,
                [d for d in os.listdir(repo_unzip_dir) if os.path.isdir(os.path.join(repo_unzip_dir, d))][0],
            )

            # Download and extract the dist artifact if available
            print("Downloading plotly.js dist artifact from:", dist_artifact_url)
            dist_archive_path = os.path.join(temp_dir, "dist.zip")
            # The dist artifact extracts its contents (plotly.min.js, plot-schema.json, ...)
            # directly at the root of the extraction directory
            dist_dir = download_and_extract_tarball(
                dist_artifact_url, dist_archive_path, headers=github_auth_headers()
            )

            # Copy the extracted dist files to the appropriate location in the extracted repo
            target_dist_dir = os.path.join(repo_extracted_path, "dist")
            shutil.copytree(dist_dir, target_dist_dir, dirs_exist_ok=True)

            # Get paths to the bundle and schema files
            bundle_path = os.path.join(repo_extracted_path, "dist", "plotly.min.js")
            schema_path = os.path.join(repo_extracted_path, "dist", "plot-schema.json")

            # Update bundle and schema in package_data
            overwrite_bundle_local(bundle_path)
            overwrite_schema_local(schema_path)

        else:
            # this info could be more informative but it doesn't seem as
            # useful in a local context and requires dependencies and
            # programming.
            build_info = {"vcs_revision": "local", "committer_date": str(time.time())}
            args.devrepo = args.local
            args.devbranch = ""

            archive_uri, bundle_uri, schema_uri = get_bundle_schema_local(args.local)
            overwrite_bundle_local(bundle_uri)
            overwrite_schema_local(schema_uri)

        # Update plotly.js url in package.json
        package_json_path = os.path.join(NODE_ROOT, "package.json")
        with open(package_json_path, "r") as f:
            package_json = json.load(f)

        print("Updating package.json to use plotly.js from:", repo_extracted_path if args.local is None else archive_uri)

        # Replace version with bundle url
        package_json["dependencies"]["plotly.js"] = (
            repo_extracted_path if args.local is None else archive_uri
        )
        with open(package_json_path, "w") as f:
            json.dump(package_json, f, indent=2)

        # update plotly.js version in _plotlyjs_version
        rev = build_info["vcs_revision"]
        date = str(build_info["committer_date"])
        version = "_".join([args.devrepo, args.devbranch, date[:10], rev[:8]])
        overwrite_plotlyjs_version_file(version)
        # install_js_deps(args.local)
        install_js_deps(archive_uri if args.local is None else None)


def update_plotlyjs_dev(args, outdir):
    """Update project to a new development version of plotly.js."""

    update_schema_bundle_from_branch(args)
    perform_codegen(outdir)


def bump_version_pyproject_toml(new_version):
    """
    Bump the version in pyproject.toml to new_version
    Returns True on success, False on failure
    """
    pyproject_toml_path = "pyproject.toml"
    pattern = r'(^\s*version\s*=\s*")([\w.]+)"(\s*$)'
    with open(pyproject_toml_path, "r") as f:
        content = f.read()
    new_content, n_subs = re.subn(
        pattern,
        rf'\g<1>{new_version}"\g<3>',
        content,
        count=1,  # replace only the first match
        flags=re.MULTILINE,
    )
    if n_subs < 1:
        print(
            f"FAILED to update version in {pyproject_toml_path}.",
            "Please update manually and then run `uv lock`.",
        )
        return False

    with open(pyproject_toml_path, "w") as f:
        f.write(new_content)

    # Run `uv lock` to update the version number in the `uv.lock` file (do not update manually)
    subprocess.run(["uv", "lock"], check=True)

    print(
        f"SUCCESS: Updated version in {pyproject_toml_path} to {new_version},",
        "and updated uv lockfile",
    )
    return True


def bump_version_package_json(new_version):
    """
    Bump the version in package.json to new_version
    Returns True on success, False on failure
    """
    js_dir = "js"
    subprocess.run(
        ["npm", "version", new_version, "--no-git-tag-version", "--allow-same-version"],
        cwd=js_dir,
        check=True,
    )
    print(
        f"SUCCESS: Updated version in {js_dir}/package.json and {js_dir}/package-lock.json to {new_version}"
    )

    # After modifying files in js/, we need to rebuild the JupyterLab extension
    print("Rebuilding JupyterLab extension (this may take a few seconds)...")
    subprocess.run(
        ["npm", "run", "build:labextension"],
        cwd=js_dir,
        check=True,
        stdout=subprocess.DEVNULL,  # Suppress stdout and stderr to avoid terminal clutter
        stderr=subprocess.DEVNULL,
    )
    print(f"SUCCESS: Updated JupyterLab extension files in plotly/labextension")

    return True


def bump_version_citation_cff(new_version, new_date):
    """
    Bump the version in CITATION.cff to new_version and date-released to new_date
    Returns True on success, False on failure
    """
    citation_cff_path = "CITATION.cff"
    pattern_version = r"(^\s*version\s*:\s*)([\w.]+)(\s*$)"
    pattern_date = r"(^\s*date-released\s*:\s*)([0-9\-]+)(\s*$)"

    with open(citation_cff_path, "r") as f:
        content = f.read()
    new_content, n_subs = re.subn(
        pattern_version,
        rf"\g<1>{new_version}\g<3>",
        content,
        count=1,  # replace only the first match
        flags=re.MULTILINE,
    )
    if n_subs < 1:
        print(
            f"FAILED to update version in {citation_cff_path}.",
            "Please update manually.",
        )
        return False
    new_content, n_subs = re.subn(
        pattern_date,
        rf"\g<1>{new_date}\g<3>",
        new_content,
        count=1,  # replace only the first match
        flags=re.MULTILINE,
    )
    if n_subs < 1:
        print(
            f"FAILED to update date-released in {citation_cff_path}.",
            "Please update manually.",
        )
        return False

    with open(citation_cff_path, "w") as f:
        f.write(new_content)
    print(
        f"SUCCESS: Updated version in {citation_cff_path} to {new_version}",
        f"and date-released to {new_date}",
    )
    return True


def bump_version_changelog_md(new_version, new_date):
    """
    Bump the version in CHANGELOG.md to new_version and date to new_date
    Returns True on success, False on failure
    """
    changelog_md_path = "CHANGELOG.md"
    pattern = r"(^\s*##\s*Unreleased\s*$)"
    new_header = f"\n\n## [{new_version}] - {new_date}\n"

    with open(changelog_md_path, "r") as f:
        content = f.read()

    # Check if the header already exists, so that we don't add a double header
    already_exists_pattern = rf"(^\s*##\s*\[ *{re.escape(new_version)} *\])"
    if re.search(already_exists_pattern, content, flags=re.MULTILINE):
        print(
            f"Header for version {new_version} already exists",
            f"in {changelog_md_path}.",
        )
        return True

    new_content, n_subs = re.subn(
        pattern,
        rf"\g<1>{new_header}",
        content,
        count=1,  # replace only the first match
        flags=re.MULTILINE,
    )
    if n_subs < 1:
        print(
            f"FAILED to update version in {changelog_md_path}.",
            "Please update manually.",
        )
        return False

    with open(changelog_md_path, "w") as f:
        f.write(new_content)
    print(
        f"Added header in {changelog_md_path} with version {new_version}",
        f"and release date {new_date}",
    )
    return True


def bump_version(args):
    """Bump the version of plotly.py everywhere it needs to be updated."""
    new_version = args.version
    new_date = time.strftime("%Y-%m-%d")

    success = True

    success = success and bump_version_citation_cff(new_version, new_date)
    success = success and bump_version_changelog_md(new_version, new_date)
    success = success and bump_version_package_json(new_version)
    # Do this one last since it's the most visible,
    # so that if one of the above commands fails it will be easier to notice
    success = success and bump_version_pyproject_toml(new_version)

    if not success:
        print(
            "\n\n*** FAILED to update version for at least one file.",
            "Please check the output above for details. ***\n\n",
        )
        exit(1)

    print(
        f"\n\n*** SUCCESSFULLY updated version to {new_version}.",
        "Please verify the result using `git diff`. ***\n\n",
    )


def make_parser():
    """Make argument parser."""

    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="cmd", help="Available subcommands")

    p_codegen = subparsers.add_parser("codegen", help="generate code")
    p_codegen.add_argument(
        "--noformat", action="store_true", help="prevent reformatting"
    )

    subparsers.add_parser("lint", help="lint code")

    subparsers.add_parser("format", help="reformat code")

    p_update_dev = subparsers.add_parser(
        "updateplotlyjsdev", help="update plotly.js for development"
    )
    p_update_dev.add_argument(
        "--devrepo", default="plotly/plotly.js", help="repository"
    )
    p_update_dev.add_argument("--devbranch", default="master", help="branch")
    p_update_dev.add_argument("--local", default=None, help="local path")

    subparsers.add_parser("updateplotlyjs", help="update plotly.js")

    p_bump_version = subparsers.add_parser("bumpversion", help="bump plotly.py version")
    # Add a positional argument for the version
    p_bump_version.add_argument("version", help="version number")

    return parser


def parse_args(parser: argparse.ArgumentParser):
    """Parse command line arguments."""
    return parser.parse_args()


def main():
    """Main driver."""

    project_root = os.path.dirname(os.path.realpath(__file__))
    outdir = os.path.join(project_root, "plotly")

    parser = make_parser()
    args = parse_args(parser)

    if args.cmd == "codegen":
        perform_codegen(outdir, noformat=args.noformat)

    elif args.cmd == "format":
        reformat_code(outdir)

    elif args.cmd == "lint":
        lint_code(outdir)

    elif args.cmd == "updateplotlyjsdev":
        update_plotlyjs_dev(args, outdir)

    elif args.cmd == "updateplotlyjs":
        version = plotly_js_version()
        print(version)
        update_plotlyjs(version, outdir)

    elif args.cmd == "bumpversion":
        bump_version(args)

    elif args.cmd is None:
        parser.print_help()
        sys.exit(1)

    else:
        print(f"unknown command {args.cmd}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
