package:
  name: plotly
  version: "1.12.4"

source:
  fn: plotly-1.12.4.tar.gz
  url: https://files.pythonhosted.org/packages/02/e0/5b739403c3180298ebe277cbc9f5ee99e546ab24768b1732a2d6b381091b/plotly-1.12.4.tar.gz
  md5: f1ff6b1b18554258aab50449ab571ee2
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - plotly = plotly:main
    #
    # Would create an entry point called plotly that calls plotly.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests
    - six
    - pytz

  run:
    - python
    - requests
    - six
    - pytz
    - matplotlib
    - numpy
    - ipython
    - ipywidgets

test:
  # Python imports
  imports:
    - plotly
    - plotly.graph_objs
    - plotly.grid_objs
    - plotly.matplotlylib
    - plotly.matplotlylib.mplexporter
    - plotly.matplotlylib.mplexporter.renderers
    - plotly.offline
    - plotly.plotly
    - plotly.plotly.chunked_requests
    - plotly.widgets

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://plot.ly/python/
  license: MIT
  summary: 'Python plotting library for collaborative, interactive, publication-quality graphs.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
