site_name: "Plotly.py Docs"
docs_dir: pages
site_dir: docs

plugins:
  - search
  - gen-files:
      scripts:
        - bin/generate_reference_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true

nav:
- Home: index.md
- API Reference: reference/
- Project:
  - license.md
  - conduct.md
  - contributing.md

theme:
  name: "material"

markdown_extensions:
- def_list
- markdown_include.include:
    base_path: docs
- footnotes

exclude_docs: >
  *~
