site_name: "Plotly.py"
site_url: 'https://plotly.com/python/'
docs_dir: pages
site_dir: docs

validation:
  absolute_links: relative_to_docs
  anchors: info
  unrecognized_links: info
  not_found: info

plugins:
  - search
  # - gen-files:
  #     scripts:
  #       - bin/generate_graph_objects_docs.py
        # - bin/generate_reference_pages.py
  # - literate-nav:
  #     nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            preload_modules:
              - _plotly_utils
            docstring_style: numpy
            show_source: false
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true

extra_css:
  - css/plotly-styles.css
  - https://docs.plotly.com/css/plotly-style.css

nav:
- Home: index.md
- Quick Reference:
  - Getting Started: examples/getting-started.md
  - Is Plotly Free?: is-plotly-free.md
  - Changelog: https://github.com/plotly/plotly.py/releases
  - Plotly Community Forum: https://community.plotly.com
  - Dash: https://dash.plotly.com
- Examples:
  - Fundamentals:
    - The Figure Data Structure: examples/figure-structure.md
    - Creating and Updating Figures: examples/creating-and-updating-figures.md
    - Displaying Figures: examples/renderers.md
    - Plotly Express: examples/plotly-express.md
    - Analytical Apps with Dash: https://dash.plotly.com/
    - Static Image Export: examples/static-image-export.md
    - Theming and templates: examples/templates.md
    - Changes in Version 6: examples/v6-changes.md
    - Configuration: examples/configuration-options.md
    - Setting Graph Size: examples/setting-graph-size.md
    - Formatting Ticks: examples/tick-formatting.md
    - Setting the Font, Title, Legend Entries, and Axis Titles: examples/figure-labels.md
    - Axes: examples/axes.md
    - Legends: examples/legend.md
    - Multiple Axes: examples/multiple-axes.md
    - Subplots: examples/subplots.md
    - Multiple Chart Types: examples/graphing-multiple-chart-types.md
    - Plotly Express Arguments: examples/px-arguments.md
    - Styling Markers: examples/marker-style.md
    - Continuous Color Scales and Color Bars: examples/colorscales.md
    - Text and Annotations: examples/text-and-annotations.md
    - Hover Text and Formatting: examples/hover-text-and-formatting.md
    - Images: examples/images.md
    - Shapes: examples/shapes.md
    - IPython vs Python: examples/ipython-vs-python.md
    - Troubleshooting: examples/troubleshooting.md
    - Built-in Continuous Color Scales: examples/builtin-colorscales.md
    - Discrete Colors: examples/discrete-color.md
    - Styling Plotly Express Figures: examples/styling-plotly-express.md
    - Interactive HTML Export: examples/interactive-html-export.md
    - Pandas Plotting Backend: examples/pandas-backend.md
    - Figure Factories: examples/figure-factories.md
    - Plotly Express Wide-Form Support: examples/wide-form.md
    - Graph Objects: examples/graph-objects.md
    - Introspecting Figures: examples/figure-introspection.md
    - Horizontal and Vertical Lines and Rectangles: examples/horizontal-vertical-shapes.md
    - Selections: examples/selections.md
    - Version 4 Migration Guide: examples/v4-migration.md
    - Static Image Generation Changes in Plotly.py 6.1: examples/static-image-generation-migration.md
    - Supported CSS Colors: examples/supported-colors.md
  - Basic Charts:
    - Scatter Plots: examples/line-and-scatter.md
    - Line Charts: examples/line-charts.md
    - Bar Charts: examples/bar-charts.md
    - Pie Charts: examples/pie-charts.md
    - Bubble Charts: examples/bubble-charts.md
    - Dot Plots: examples/dot-plots.md
    - Filled Area Plots: examples/filled-area-plots.md
    - Horizontal Bar Charts: examples/horizontal-bar-charts.md
    - Gantt Charts: examples/gantt.md
    - Sunburst Charts: examples/sunburst-charts.md
    - Tables: examples/table.md
    - Sankey Diagram: examples/sankey-diagram.md
    - Treemap Charts: examples/treemaps.md
    - High Performance Visualization: examples/performance.md
    - Figure Factory Tables: examples/figure-factory-table.md
    - Categorical Axes: examples/categorical-axes.md
    - Icicle Charts: examples/icicle-charts.md
    - Patterns, Hatching, Texture: examples/pattern-hatching-texture.md
    - Dumbbell Plots: examples/dumbbell-plots.md
  - Statistical Charts:
    - Error Bars: examples/error-bars.md
    - Box Plots: examples/box-plots.md
    - Histograms: examples/histograms.md
    - Distplots: examples/distplot.md
    - 2D Histograms: examples/2D-Histogram.md
    - Scatterplot Matrix: examples/splom.md
    - Facet and Trellis Plots: examples/facet-plots.md
    - Parallel Categories Diagram: examples/parallel-categories-diagram.md
    - Tree-plots: examples/tree-plots.md
    - Violin Plots: examples/violin.md
    - 2D Histogram Contour: examples/2d-histogram-contour.md
    - Linear and Non-Linear Trendlines: examples/linear-fits.md
    - Marginal Distribution Plots: examples/marginal-plots.md
    - Strip Charts: examples/strip-charts.md
    - Continuous Error Bands: examples/continuous-error-bars.md
    - Empirical Cumulative Distribution Plots: examples/ecdf-plots.md
  - Scientific Charts:
    - Contour Plots: examples/contour-plots.md
    - Heatmaps: examples/heatmaps.md
    - Imshow: examples/imshow.md
    - Ternary Plots: examples/ternary-plots.md
    - Log Plots: examples/log-plot.md
    - Dendrograms: examples/dendrogram.md
    - Annotated Heatmaps: examples/annotated-heatmap.md
    - Ternary Overlay: examples/ternary-scatter-contour.md
    - Parallel Coordinates Plot: examples/parallel-coordinates-plot.md
    - Quiver Plots: examples/quiver-plots.md
    - Streamline Plots: examples/streamline-plots.md
    - Network Graphs: examples/network-graphs.md
    - Carpet Plots: examples/carpet-plot.md
    - Carpet Contour Plot: examples/carpet-contour.md
    - Carpet Scatter Plot: examples/carpet-scatter.md
    - Polar Charts: examples/polar-chart.md
    - Radar Charts: examples/radar-chart.md
    - Ternary contours: examples/ternary-contour.md
    - Wind Rose and Polar Bar Charts: examples/wind-rose-charts.md
    - Smith Charts: examples/smith-charts.md
  - Financial Charts:
    - Time Series and Date Axes: examples/time-series.md
    - Candlestick Charts: examples/candlestick-charts.md
    - Waterfall Charts: examples/waterfall-charts.md
    - Funnel Chart: examples/funnel-charts.md
    - OHLC Charts: examples/ohlc-charts.md
    - Indicators: examples/indicator.md
    - Gauge Charts: examples/gauge-charts.md
    - Bullet Charts: examples/bullet-charts.md
  - Maps:
    - MapLibre Migration: examples/migrate-to-maplibre.md
    - Tile Choropleth Maps: examples/tile-county-choropleth.md
    - Lines on Tile Maps: examples/lines-on-tile-maps.md
    - Filled Area on Tile Maps: examples/filled-area-tile-maps.md
    - Bubble Maps: examples/bubble-maps.md
    - Density Heatmap: examples/density-heatmaps.md
    - Lines on Maps: examples/lines-on-maps.md
    - Choropleth Maps: examples/choropleth-maps.md
    - Tile Map Layers: examples/tile-map-layers.md
    - Scatter Plots on Tile Maps: examples/tile-scatter-maps.md
    - USA County Choropleth Maps: examples/county-choropleth.md
    - Scatter Plots on Maps: examples/scatter-plots-on-maps.md
    - Map Configuration and Styling on Geo Maps: examples/map-configuration.md
    - Hexbin Mapbox: examples/hexbin-mapbox.md
  - AI & ML:
    - ML Regression: examples/ml-regression.md
    - kNN Classification: examples/ml-knn.md
    - ROC and PR Curves: examples/ml-roc-pr.md
    - PCA Visualization: examples/ml-pca.md
    - AI/ML Apps with Dash: https://plotly.com/building-machine-learning-web-apps-in-python/
    - t-SNE and UMAP projections: examples/ml-tsne-umap-projections.md
  - Visualizing Biological Data:
    - Volcano Plot: examples/bio-volcano-plot.md
    - Manhattan Plot: examples/bio-manhattanplot.md
    - Clustergram: examples/bio-clustergram.md
    - Alignment Chart: examples/bio-alignment-chart.md
  - 3D Charts:
    - 3D Axes: examples/3d-axes.md
    - 3D Scatter Plots: examples/3d-scatter-plots.md
    - 3D Surface Plots: examples/3d-surface-plots.md
    - 3D Subplots: examples/3d-subplots.md
    - 3D Camera Controls: examples/3d-camera-controls.md
    - 3D Bubble Charts: examples/3d-bubble-charts.md
    - 3D Line Plots: examples/3d-line-plots.md
    - Trisurf Plots: examples/trisurf.md
    - 3D Mesh Plots: examples/3d-mesh.md
    - 3D Isosurface Plots: examples/3d-isosurface-plots.md
    - 3D Volume Plots: examples/3d-volume.md
    - 3D Cone Plots: examples/cone-plot.md
    - 3D Streamtube Plots: examples/streamtube-plot.md
  - Subplots:
    - Mixed Subplots: examples/mixed-subplots.md
    - Map Subplots: examples/map-subplots-and-small-multiples.md
    - Table and Chart Subplots: examples/table-subplots.md
    - Figure Factory Subplots: examples/figure-factory-subplots.md
  - Jupyter Widgets Interaction:
    - Plotly FigureWidget Overview: examples/figurewidget.md
    - Jupyter Lab with FigureWidget: examples/jupyter-lab-tools.md
    - Interactive Data Analysis with FigureWidget ipywidgets: examples/figurewidget-app.md
    - Click Events: examples/click-events.md
  - Animations:
    - Intro to Animations: examples/animations.md
  - Controls:
    - Custom Buttons: examples/custom-buttons.md
    - Sliders: examples/sliders.md
    - Dropdown Menus: examples/dropdowns.md
    - Range Slider and Selector: examples/range-slider.md
  - Advanced:
    - Plot CSV Data: examples/plot-data-from-csv.md
    - Random Walk: examples/random-walk.md
    - Peak Finding: examples/peak-finding.md
    - Smoothing: examples/smoothing.md
    - LaTeX: examples/LaTeX.md
- API Reference:
    - plotly.graph_objects:
      - Overview: reference/graph_objects/index.md
      - Core Objects:
        - Figure: reference/graph_objects/Figure.md
        - Layout: reference/graph_objects/Layout.md
      - Simple Traces:
        - Bar: reference/graph_objects/Bar.md
        - Contour: reference/graph_objects/Contour.md
        - Heatmap: reference/graph_objects/Heatmap.md
        - Image: reference/graph_objects/Image.md
        - Pie: reference/graph_objects/Pie.md
        - Scatter: reference/graph_objects/Scatter.md
        - Scattergl: reference/graph_objects/Scattergl.md
        - Table: reference/graph_objects/Table.md
      - Distribution Traces:
        - Box: reference/graph_objects/Box.md
        - Histogram: reference/graph_objects/Histogram.md
        - Histogram2d: reference/graph_objects/Histogram2d.md
        - Histogram2dContour: reference/graph_objects/Histogram2dContour.md
        - Violin: reference/graph_objects/Violin.md
      - Finance Traces:
        - Candlestick: reference/graph_objects/Candlestick.md
        - Funnel: reference/graph_objects/Funnel.md
        - Funnelarea: reference/graph_objects/Funnelarea.md
        - Indicator: reference/graph_objects/Indicator.md
        - Ohlc: reference/graph_objects/Ohlc.md
        - Waterfall: reference/graph_objects/Waterfall.md
      - 3D Traces:
        - Cone: reference/graph_objects/Cone.md
        - Isosurface: reference/graph_objects/Isosurface.md
        - Mesh3d: reference/graph_objects/Mesh3d.md
        - Scatter3d: reference/graph_objects/Scatter3d.md
        - Streamtube: reference/graph_objects/Streamtube.md
        - Surface: reference/graph_objects/Surface.md
        - Volume: reference/graph_objects/Volume.md
      - Map Traces:
        - Choropleth: reference/graph_objects/Choropleth.md
        - Choroplethmap: reference/graph_objects/Choroplethmap.md
        - Choroplethmapbox: reference/graph_objects/Choroplethmapbox.md
        - Densitymap: reference/graph_objects/Densitymap.md
        - Densitymapbox: reference/graph_objects/Densitymapbox.md
        - Scattergeo: reference/graph_objects/Scattergeo.md
        - Scattermap: reference/graph_objects/Scattermap.md
        - Scattermapbox: reference/graph_objects/Scattermapbox.md
      - Specialized Traces:
        - Barpolar: reference/graph_objects/Barpolar.md
        - Carpet: reference/graph_objects/Carpet.md
        - Contourcarpet: reference/graph_objects/Contourcarpet.md
        - Icicle: reference/graph_objects/Icicle.md
        - Parcats: reference/graph_objects/Parcats.md
        - Parcoords: reference/graph_objects/Parcoords.md
        - Sankey: reference/graph_objects/Sankey.md
        - Scattercarpet: reference/graph_objects/Scattercarpet.md
        - Scatterpolar: reference/graph_objects/Scatterpolar.md
        - Scatterpolargl: reference/graph_objects/Scatterpolargl.md
        - Scattersmith: reference/graph_objects/Scattersmith.md
        - Scatterternary: reference/graph_objects/Scatterternary.md
        - Splom: reference/graph_objects/Splom.md
        - Sunburst: reference/graph_objects/Sunburst.md
        - Treemap: reference/graph_objects/Treemap.md
      - Other Classes:
        - FigureWidget: reference/graph_objects/FigureWidget.md
        - Frame: reference/graph_objects/Frame.md
      - Modules:
        - bar: reference/graph_objects/bar-package/index.md
        - barpolar: reference/graph_objects/barpolar-package/index.md
        - box: reference/graph_objects/box-package/index.md
        - candlestick: reference/graph_objects/candlestick-package/index.md
        - carpet: reference/graph_objects/carpet-package/index.md
        - choropleth: reference/graph_objects/choropleth-package/index.md
        - choroplethmap: reference/graph_objects/choroplethmap-package/index.md
        - choroplethmapbox: reference/graph_objects/choroplethmapbox-package/index.md
        - cone: reference/graph_objects/cone-package/index.md
        - contour: reference/graph_objects/contour-package/index.md
        - contourcarpet: reference/graph_objects/contourcarpet-package/index.md
        - densitymap: reference/graph_objects/densitymap-package/index.md
        - densitymapbox: reference/graph_objects/densitymapbox-package/index.md
        - funnel: reference/graph_objects/funnel-package/index.md
        - funnelarea: reference/graph_objects/funnelarea-package/index.md
        - heatmap: reference/graph_objects/heatmap-package/index.md
        - histogram: reference/graph_objects/histogram-package/index.md
        - histogram2d: reference/graph_objects/histogram2d-package/index.md
        - histogram2dcontour: reference/graph_objects/histogram2dcontour-package/index.md
        - icicle: reference/graph_objects/icicle-package/index.md
        - image: reference/graph_objects/image-package/index.md
        - indicator: reference/graph_objects/indicator-package/index.md
        - isosurface: reference/graph_objects/isosurface-package/index.md
        - layout: reference/graph_objects/layout-package/index.md
        - mesh3d: reference/graph_objects/mesh3d-package/index.md
        - ohlc: reference/graph_objects/ohlc-package/index.md
        - parcats: reference/graph_objects/parcats-package/index.md
        - parcoords: reference/graph_objects/parcoords-package/index.md
        - pie: reference/graph_objects/pie-package/index.md
        - sankey: reference/graph_objects/sankey-package/index.md
        - scatter: reference/graph_objects/scatter-package/index.md
        - scatter3d: reference/graph_objects/scatter3d-package/index.md
        - scattercarpet: reference/graph_objects/scattercarpet-package/index.md
        - scattergeo: reference/graph_objects/scattergeo-package/index.md
        - scattergl: reference/graph_objects/scattergl-package/index.md
        - scattermap: reference/graph_objects/scattermap-package/index.md
        - scattermapbox: reference/graph_objects/scattermapbox-package/index.md
        - scatterpolar: reference/graph_objects/scatterpolar-package/index.md
        - scatterpolargl: reference/graph_objects/scatterpolargl-package/index.md
        - scattersmith: reference/graph_objects/scattersmith-package/index.md
        - scatterternary: reference/graph_objects/scatterternary-package/index.md
        - splom: reference/graph_objects/splom-package/index.md
        - streamtube: reference/graph_objects/streamtube-package/index.md
        - sunburst: reference/graph_objects/sunburst-package/index.md
        - surface: reference/graph_objects/surface-package/index.md
        - table: reference/graph_objects/table-package/index.md
        - treemap: reference/graph_objects/treemap-package/index.md
        - violin: reference/graph_objects/violin-package/index.md
        - volume: reference/graph_objects/volume-package/index.md
        - waterfall: reference/graph_objects/waterfall-package/index.md
- Project:
  - license.md
  - conduct.md
  - contributing.md

not_in_nav: |
  reference/graph_objects/*-package/*

theme:
  name: "material"
  custom_dir: "pages/overrides"
  font:
  text: Inter
  features:
    - navigation.sections
    - content.code.copy
    - content.code.annotate
  logo: https://docs.plotly.com/assets/plotly_logo_square.png
  palette:
    # Auto (follows system)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
- def_list
- markdown_include.include:
    base_path: docs
- footnotes
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

exclude_docs: |
  *~
  examples/dash.md
  examples/ml_apps.md
  examples/orca-management.md