import sys
from _plotly_utils.importers import relative_import

__all__, __getattr__, __dir__ = relative_import(
    __name__,
    [],
    [
        "._visible.VisibleValidator",
        "._tickwidth.TickwidthValidator",
        "._tickvalssrc.TickvalssrcValidator",
        "._tickvals.TickvalsValidator",
        "._ticktextsrc.TicktextsrcValidator",
        "._ticktext.TicktextValidator",
        "._ticksuffix.TicksuffixValidator",
        "._ticks.TicksValidator",
        "._tickprefix.TickprefixValidator",
        "._tickmode.TickmodeValidator",
        "._ticklen.TicklenValidator",
        "._ticklabelstep.TicklabelstepValidator",
        "._tickformatstopdefaults.TickformatstopdefaultsValidator",
        "._tickformatstops.TickformatstopsValidator",
        "._tickformat.TickformatValidator",
        "._tickfont.TickfontValidator",
        "._tickcolor.TickcolorValidator",
        "._tickangle.TickangleValidator",
        "._tick0.Tick0Validator",
        "._showticksuffix.ShowticksuffixValidator",
        "._showtickprefix.ShowtickprefixValidator",
        "._showticklabels.ShowticklabelsValidator",
        "._showexponent.ShowexponentValidator",
        "._separatethousands.SeparatethousandsValidator",
        "._range.RangeValidator",
        "._nticks.NticksValidator",
        "._minexponent.MinexponentValidator",
        "._labelalias.LabelaliasValidator",
        "._exponentformat.ExponentformatValidator",
        "._dtick.DtickValidator",
    ],
)
