# Configuration for generating plotly.graph_objects reference pages
# Based on the Sphinx autosummary structure

title: "plotly.graph_objects: low-level interface to figures, traces and layout"
description: "plotly.graph_objects contains the building blocks of plotly Figure: traces and Layout"

sections:
  - name: "Figure"
    description: ""
    items:
      - name: "Figure"
        type: "class"
        options:
          merge_init_into_class: true
          inherited_members: true

  - name: "Layout"
    description: ""
    items:
      - name: "Layout"
        type: "class"

  - name: "Simple Traces"
    description: ""
    items:
      - name: "Scatter"
        type: "trace"
      - name: "Scattergl"
        type: "trace"
      - name: "Bar"
        type: "trace"
      - name: "Pie"
        type: "trace"
      - name: "Heatmap"
        type: "trace"
      - name: "Image"
        type: "trace"
      - name: "Contour"
        type: "trace"
      - name: "Table"
        type: "trace"

  - name: "Distribution Traces"
    description: ""
    items:
      - name: "Box"
        type: "trace"
      - name: "Violin"
        type: "trace"
      - name: "Histogram"
        type: "trace"
      - name: "Histogram2d"
        type: "trace"
      - name: "Histogram2dContour"
        type: "trace"

  - name: "Finance Traces"
    description: ""
    items:
      - name: "Ohlc"
        type: "trace"
      - name: "Candlestick"
        type: "trace"
      - name: "Waterfall"
        type: "trace"
      - name: "Funnel"
        type: "trace"
      - name: "Funnelarea"
        type: "trace"
      - name: "Indicator"
        type: "trace"

  - name: "3D Traces"
    description: ""
    items:
      - name: "Scatter3d"
        type: "trace"
      - name: "Surface"
        type: "trace"
      - name: "Mesh3d"
        type: "trace"
      - name: "Cone"
        type: "trace"
      - name: "Streamtube"
        type: "trace"
      - name: "Volume"
        type: "trace"
      - name: "Isosurface"
        type: "trace"

  - name: "Map Traces"
    description: ""
    items:
      - name: "Scattergeo"
        type: "trace"
      - name: "Choropleth"
        type: "trace"
      - name: "Scattermap"
        type: "trace"
      - name: "Choroplethmap"
        type: "trace"
      - name: "Densitymap"
        type: "trace"
      - name: "Scattermapbox"
        type: "trace"
      - name: "Choroplethmapbox"
        type: "trace"
      - name: "Densitymapbox"
        type: "trace"

  - name: "Specialized Traces"
    description: ""
    items:
      - name: "Scatterpolar"
        type: "trace"
      - name: "Scatterpolargl"
        type: "trace"
      - name: "Barpolar"
        type: "trace"
      - name: "Scatterternary"
        type: "trace"
      - name: "Sunburst"
        type: "trace"
      - name: "Treemap"
        type: "trace"
      - name: "Icicle"
        type: "trace"
      - name: "Sankey"
        type: "trace"
      - name: "Splom"
        type: "trace"
      - name: "Parcats"
        type: "trace"
      - name: "Parcoords"
        type: "trace"
      - name: "Carpet"
        type: "trace"
      - name: "Scattercarpet"
        type: "trace"
      - name: "Contourcarpet"
        type: "trace"

