import sys
from _plotly_utils.importers import relative_import

__all__, __getattr__, __dir__ = relative_import(
    __name__,
    [],
    [
        "._zorder.ZorderValidator",
        "._ysrc.YsrcValidator",
        "._yaxis.YaxisValidator",
        "._y.YValidator",
        "._xsrc.XsrcValidator",
        "._xaxis.XaxisValidator",
        "._x.XValidator",
        "._visible.VisibleValidator",
        "._uirevision.UirevisionValidator",
        "._uid.UidValidator",
        "._stream.StreamValidator",
        "._opacity.OpacityValidator",
        "._name.NameValidator",
        "._metasrc.MetasrcValidator",
        "._meta.MetaValidator",
        "._legendwidth.LegendwidthValidator",
        "._legendrank.LegendrankValidator",
        "._legendgrouptitle.LegendgrouptitleValidator",
        "._legend.LegendValidator",
        "._idssrc.IdssrcValidator",
        "._ids.IdsValidator",
        "._font.FontValidator",
        "._db.DbValidator",
        "._da.DaValidator",
        "._customdatasrc.CustomdatasrcValidator",
        "._customdata.CustomdataValidator",
        "._color.ColorValidator",
        "._cheaterslope.CheaterslopeValidator",
        "._carpet.CarpetValidator",
        "._bsrc.BsrcValidator",
        "._baxis.BaxisValidator",
        "._b0.B0Validator",
        "._b.BValidator",
        "._asrc.AsrcValidator",
        "._aaxis.AaxisValidator",
        "._a0.A0Validator",
        "._a.AValidator",
    ],
)
