name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  plotlyjs-dev-build:
    name: plotly.js dev build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: "3.12"
      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: "22"
      - name: Set up uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4  # v10.1.0
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --extra dev_optional
      - name: Update plotly.js to dev
        run: |
          source .venv/bin/activate
          python commands.py updateplotlyjsdev
      - name: Test core (excluding nodev)
        run: |
          source .venv/bin/activate
          pytest -k 'not nodev' tests/test_core
      - name: Build source distribution packages
        run: |
          source .venv/bin/activate
          uv sync --extra dev_build
          python -m build --sdist --wheel -o dist
      - name: Upload dist artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: plotlyjs-dev-build-dist
          path: dist/
          if-no-files-found: error

  full-build:
    name: Full prod build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: "3.12"
      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: "22"
      - name: Set up uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4  # v10.1.0
      - name: PyPI Build
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --extra dev_build
          cd js
          npm ci
          npm run build
          cd ..
          python -m build --sdist --wheel -o dist
          cp -R dist output
          git status
      - name: Zip output
        run: |
          tar czf output.tgz output
      - name: Upload output artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: full-build-output
          path: output.tgz
          if-no-files-found: error
