name: Check Python code formatting

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  check-code-formatting:
    name: Run ruff check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --extra dev_core
      - name: Check handwritten code with ruff
        run: |
          source .venv/bin/activate
          ruff format --check .
