name: Check Python code formatting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  check-code-formatting:
    name: Run ruff check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4  # v10.1.0
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --extra dev_core
      - name: Check handwritten code with ruff
        run: |
          source .venv/bin/activate
          ruff format --check .
