name: Run Percy

on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  python-311-percy:
    name: Run Percy
    runs-on: ubuntu-latest
    env:
      PERCY_ENABLED: "True"
      PERCY_PROJECT: plotly/plotly.py
      PERCY_TOKEN: ${{ secrets.PERCY_PYTHON_TOKEN_V0 }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v2.1.1
        with:
          install-chromedriver: true
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Install requirements
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --extra dev_optional
      - name: Build HTML figures (Pandas 2)
        run: |
          source .venv/bin/activate
          python tests/percy/plotly-express.py
      - name: Run percy snapshots
        run: |
          npm i @percy/cli
          npx percy snapshot -c tests/percy/snapshots.yml tests/percy/
          rm tests/percy/*.html
