name: Run Percy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  python-311-percy:
    name: Run Percy
    runs-on: ubuntu-latest
    env:
      PERCY_ENABLED: "True"
      PERCY_PROJECT: plotly/plotly.py
      PERCY_TOKEN: ${{ secrets.PERCY_PYTHON_TOKEN_V0 }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.11"
      - name: Set up Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f  # v6.3.0
        with:
          node-version: "22"
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@4f8e94349a351df0f048634f25fec36c3c91eded  # v2.1.1
        with:
          install-chromedriver: true
      - name: Set up uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
      - name: Install requirements
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --extra dev_optional
      - name: Build HTML figures (Pandas 2)
        run: |
          source .venv/bin/activate
          python tests/percy/plotly-express.py
      - name: Run percy snapshots
        run: |
          npm i @percy/cli
          npx percy snapshot -c tests/percy/snapshots.yml tests/percy/
          rm tests/percy/*.html
